[tool.poetry]
name = "samrthire coach"
version = "0.1.0"
description = ""
authors = ["Dark Coder <codewithdark90@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
